# coding=utf-8
u"""
Generated API Layout Test
=========================

检查自动生成 API Reference 的最终阅读结构。

必须满足：
    1. 每个生成页面都有简短“用途 / 模块定位”；
    2. 概览不再直接铺完整 Module Docstring；
    3. 每个公开 Function / Method 标题后都有明确“作用”；
    4. 参数表不允许出现“未声明”或自动占位提示。
"""

from __future__ import print_function

import os
import re


GENERATED_MARKER = "<!-- AUTO-GENERATED BY scripts/generate_mkdocs_reference.py -->"

CALLABLE_HEADING_PATTERN = re.compile(
    r"(?m)^(#{3,6}\s+`[^`\n]+\(\)`)\s*$"
)


# =============================================================================
# Project
# =============================================================================

def get_project_root():
    u"""返回仓库根目录。"""
    tests_directory = os.path.dirname(
        os.path.abspath(__file__)
    )
    return os.path.dirname(
        tests_directory
    )


def iter_generated_reference_files(project_root):
    u"""遍历全部自动生成 API Reference Markdown。"""
    reference_root = os.path.join(
        project_root,
        "docs",
        "reference"
    )

    result = []

    for root_directory, folder_names, file_names in os.walk(reference_root):
        if "__pycache__" in folder_names:
            folder_names.remove(
                "__pycache__"
            )

        for file_name in file_names:
            if not file_name.endswith(".md"):
                continue

            file_path = os.path.join(
                root_directory,
                file_name
            )

            with open(
                    file_path,
                    "r",
                    encoding="utf-8"
            ) as file_object:
                content = file_object.read()

            if GENERATED_MARKER not in content:
                continue

            result.append(
                file_path
            )

    result.sort()
    return result


# =============================================================================
# Validate
# =============================================================================

def validate_overview(file_path, content, errors):
    u"""检查页面概览是否简短清晰。"""
    start_marker = "## 概览"
    end_marker = "## 常用任务"

    start_index = content.find(
        start_marker
    )
    end_index = content.find(
        end_marker
    )

    if start_index < 0:
        errors.append(
            u"{} 缺少概览。".format(file_path)
        )
        return

    if end_index < 0 or end_index <= start_index:
        errors.append(
            u"{} 概览结构异常。".format(file_path)
        )
        return

    overview_text = content[
        start_index:end_index
    ]

    if "**用途**" not in overview_text:
        errors.append(
            u"{} 概览缺少用途。".format(file_path)
        )

    if "**模块定位**" not in overview_text:
        errors.append(
            u"{} 概览缺少模块定位。".format(file_path)
        )

    if len(overview_text) > 700:
        errors.append(
            u"{} 概览过长，不利于快速扫读。".format(file_path)
        )


def validate_callable_purpose(file_path, content, errors):
    u"""检查每个公开 Function / Method 是否有明确“作用”。"""
    matches = list(
        CALLABLE_HEADING_PATTERN.finditer(
            content
        )
    )

    match_index = 0

    while match_index < len(matches):
        match = matches[match_index]
        section_start = match.end()
        section_end = len(content)

        if match_index + 1 < len(matches):
            section_end = matches[match_index + 1].start()

        section_text = content[
            section_start:section_end
        ]

        if "**作用**" not in section_text[:220]:
            errors.append(
                u"{} 的 {} 缺少作用说明。".format(
                    file_path,
                    match.group(1)
                )
            )

        match_index += 1

    return len(matches)


def validate_placeholders(file_path, content, errors):
    u"""检查最终 API 页面是否还残留未完成占位说明。"""
    forbidden_texts = [
        "`未声明`",
        "源码暂未提供单独参数说明",
        "源码暂未提供详细功能摘要",
    ]

    for forbidden_text in forbidden_texts:
        if forbidden_text not in content:
            continue

        errors.append(
            u"{} 仍包含占位说明: {}".format(
                file_path,
                forbidden_text
            )
        )


def run_test():
    u"""运行全部生成 API 页面的布局质量检查。"""
    project_root = get_project_root()
    generated_files = iter_generated_reference_files(
        project_root
    )

    if not generated_files:
        raise AssertionError(
            u"没有找到自动生成 API 页面，请先运行 Generator。"
        )

    errors = []
    callable_count = 0

    for file_path in generated_files:
        with open(
                file_path,
                "r",
                encoding="utf-8"
        ) as file_object:
            content = file_object.read()

        validate_overview(
            file_path,
            content,
            errors
        )

        callable_count += validate_callable_purpose(
            file_path,
            content,
            errors
        )

        validate_placeholders(
            file_path,
            content,
            errors
        )

    if callable_count <= 0:
        errors.append(
            u"没有扫描到任何公开 Function / Method。"
        )

    print(
        u"Generated API pages: {}".format(
            len(generated_files)
        )
    )
    print(
        u"Callable sections:   {}".format(
            callable_count
        )
    )

    if errors:
        print(u"Layout errors:")

        for error in errors:
            print(
                u"  - {}".format(error)
            )

        raise AssertionError(
            u"Generated API Reference 布局检查失败。"
        )

    print(u"Generated API Reference layout: PASS")
    return True


if __name__ == "__main__":
    run_test()
