# coding=utf-8
u"""
Generated API Reference Refiner
===============================

直接整理 ``docs/reference`` 中真实生成出来的 API Markdown 页面。

负责：
    1. 模块“概览”只保留简短用途说明；
    2. 概览固定分成“用途”和“模块定位”；
    3. 不把完整 Module Docstring 正文直接铺在页面顶部；
    4. 每一个公开 Function / Method 标题下面固定增加“作用”区块；
    5. 保持 Signature、参数、返回值、异常、示例和 Notes 不变。

设计说明：
    本脚本不再依赖 Generator 的“源码路径 -> 输出路径”推算。
    Generator 完成后直接扫描实际生成的 Markdown，因此新增目录、Package Page
    或 Generator 输出规则调整时，不会因为路径映射过期而静默漏处理页面。

使用顺序：
    python scripts/generate_mkdocs_reference.py
    python scripts/refine_generated_reference.py
"""

from __future__ import print_function

import ast
import os
import re


GENERATED_MARKER = "<!-- AUTO-GENERATED BY scripts/generate_mkdocs_reference.py -->"
MAX_SUMMARY_LENGTH = 140

CALLABLE_HEADING_PATTERN = re.compile(
    r"^(#{3,6})\s+`[^`]+\(\)`\s*$"
)


# =============================================================================
# Project
# =============================================================================

def get_project_root():
    u"""返回 MuziTools 仓库根目录。"""
    script_directory = os.path.dirname(
        os.path.abspath(__file__)
    )

    return os.path.dirname(
        script_directory
    )


def get_reference_root(project_root):
    u"""返回自动生成 API Reference 的根目录。"""
    return os.path.join(
        project_root,
        "docs",
        "reference"
    )


def iter_generated_reference_files(project_root):
    u"""遍历 ``docs/reference`` 下全部真实自动生成 Markdown 页面。"""
    reference_root = get_reference_root(
        project_root
    )
    result = []

    if not os.path.isdir(reference_root):
        return result

    for root_directory, folder_names, file_names in os.walk(reference_root):
        if "__pycache__" in folder_names:
            folder_names.remove(
                "__pycache__"
            )

        for file_name in file_names:
            if not file_name.endswith(".md"):
                continue

            file_path = os.path.join(
                root_directory,
                file_name
            )

            with open(
                    file_path,
                    "r",
                    encoding="utf-8"
            ) as file_object:
                prefix = file_object.read(512)

            if GENERATED_MARKER not in prefix:
                continue

            result.append(
                file_path
            )

    result.sort()
    return result


# =============================================================================
# Source Mapping
# =============================================================================

def get_source_path_from_reference(project_root, markdown_path):
    u"""
    根据生成页面路径反向取得对应 Runtime Python 源码。

    映射示例：
        ``docs/reference/core/attr_utils.md``
            -> ``core/attr_utils.py``

        ``docs/reference/systems/face/package.md``
            -> ``systems/face/__init__.py``

        ``docs/reference/package.md``
            -> ``__init__.py``

    分类 ``index.md`` 没有单一源码来源，因此返回 None。
    """
    reference_root = get_reference_root(
        project_root
    )
    relative_path = os.path.relpath(
        markdown_path,
        reference_root
    )
    relative_path = relative_path.replace(
        "\\",
        "/"
    )

    if relative_path == "package.md":
        source_path = os.path.join(
            project_root,
            "__init__.py"
        )

    elif relative_path == "config.md":
        source_path = os.path.join(
            project_root,
            "config.py"
        )

    elif relative_path.endswith("/package.md"):
        package_directory = relative_path[:-len("/package.md")]
        source_path = os.path.join(
            project_root,
            package_directory,
            "__init__.py"
        )

    elif relative_path.endswith("/index.md"):
        return None

    else:
        source_relative_path = os.path.splitext(
            relative_path
        )[0] + ".py"
        source_path = os.path.join(
            project_root,
            source_relative_path
        )

    if not os.path.isfile(source_path):
        return None

    return source_path


# =============================================================================
# Summary
# =============================================================================

def is_underline_heading(line):
    u"""判断一行是否是 ReStructuredText 风格标题下划线。"""
    stripped_line = line.strip()

    if not stripped_line:
        return False

    characters = set(stripped_line)

    if characters == set("="):
        return True

    if characters == set("-"):
        return True

    return False


def looks_like_section_title(paragraph):
    u"""判断自然段是否更像章节标题，而不是模块用途摘要。"""
    section_titles = [
        "模块职责",
        "当前公开方法",
        "公开类",
        "主要公开方法",
        "兼容辅助方法",
        "数据流",
        "本模块不负责",
        "设计原则",
        "正式模块路径",
        "生成范围",
        "说明",
        "功能",
        "使用场景",
        "职责",
        "边界",
        "负责",
        "使用",
    ]

    normalized = paragraph.strip().rstrip(":：")

    if normalized in section_titles:
        return True

    if len(normalized) <= 18:
        for title in section_titles:
            if title in normalized:
                return True

    # ``Animation Utils``、``Face Guide`` 这一类英文模块标题不适合作为用途。
    if len(normalized) <= 48:
        if re.match(
                r"^[A-Za-z0-9_ /.+-]+$",
                normalized
        ):
            return True

    return False


def get_docstring_paragraphs(docstring):
    u"""把 Module Docstring 整理成可用于摘要选择的自然段。"""
    if not docstring:
        return []

    raw_lines = docstring.expandtabs(4).strip().splitlines()
    clean_lines = []
    line_index = 0

    while line_index < len(raw_lines):
        line = raw_lines[line_index]
        stripped_line = line.strip()
        next_line = ""

        if line_index + 1 < len(raw_lines):
            next_line = raw_lines[line_index + 1]

        if stripped_line and is_underline_heading(next_line):
            line_index += 2
            continue

        if is_underline_heading(line):
            line_index += 1
            continue

        clean_lines.append(
            line.rstrip()
        )
        line_index += 1

    paragraphs = []
    current_lines = []

    for line in clean_lines:
        stripped_line = line.strip()

        if not stripped_line:
            if current_lines:
                paragraphs.append(
                    " ".join(current_lines).strip()
                )
                current_lines = []
            continue

        current_lines.append(
            stripped_line
        )

    if current_lines:
        paragraphs.append(
            " ".join(current_lines).strip()
        )

    return paragraphs


def trim_summary(summary):
    u"""把用途摘要控制在最多两句话、140 字符以内。"""
    summary = " ".join(
        summary.split()
    ).strip()

    if not summary:
        return summary

    sentence_parts = re.split(
        r"(?<=[。！？.!?])\s*",
        summary
    )
    selected_sentences = []

    for sentence in sentence_parts:
        sentence = sentence.strip()

        if not sentence:
            continue

        selected_sentences.append(
            sentence
        )

        if len(selected_sentences) >= 2:
            break

    if selected_sentences:
        summary = " ".join(
            selected_sentences
        )

    if len(summary) > MAX_SUMMARY_LENGTH:
        summary = summary[:MAX_SUMMARY_LENGTH - 3].rstrip()
        summary += "..."

    return summary


def build_summary_from_source(source_path):
    u"""从对应 Runtime 源码的 Module Docstring 中提取简短用途。"""
    if not source_path:
        return ""

    with open(
            source_path,
            "r",
            encoding="utf-8"
    ) as file_object:
        source_text = file_object.read()

    module_tree = ast.parse(
        source_text,
        filename=source_path
    )
    module_docstring = ast.get_docstring(
        module_tree
    ) or ""

    paragraphs = get_docstring_paragraphs(
        module_docstring
    )

    for paragraph in paragraphs:
        if looks_like_section_title(paragraph):
            continue

        if paragraph.startswith("``"):
            continue

        summary = trim_summary(
            paragraph
        )

        if summary:
            return summary

    return ""


def extract_summary_from_overview(markdown_text):
    u"""没有单一源码来源时，从现有生成概览选择一个简短摘要。"""
    start_marker = "## 概览"
    end_marker = "## 常用任务"

    start_index = markdown_text.find(
        start_marker
    )
    end_index = markdown_text.find(
        end_marker
    )

    if start_index < 0 or end_index <= start_index:
        return "MuziTools 自动生成的 API Reference 分类页面。"

    overview_text = markdown_text[
        start_index + len(start_marker):end_index
    ]
    paragraphs = overview_text.split("\n\n")

    for paragraph in paragraphs:
        paragraph = " ".join(
            paragraph.split()
        ).strip()

        if not paragraph:
            continue

        if paragraph.startswith("**"):
            continue

        if paragraph.startswith("#"):
            continue

        if looks_like_section_title(paragraph):
            continue

        summary = trim_summary(
            paragraph
        )

        if summary:
            return summary

    return "MuziTools 自动生成的 API Reference 分类页面。"


def build_module_position(markdown_path, project_root):
    u"""根据真实 API 页面目录生成简洁的模块层级定位。"""
    reference_root = get_reference_root(
        project_root
    )
    relative_path = os.path.relpath(
        markdown_path,
        reference_root
    )
    relative_path = relative_path.replace(
        "\\",
        "/"
    )

    if relative_path.startswith("core/"):
        return u"Core 底层公共能力；不负责 UI 和完整 Rig Workflow。"

    if relative_path.startswith("systems/"):
        return u"System 业务构建层；负责可重复构建的完整 Rig Component 或 Workflow。"

    if relative_path.startswith("tools/"):
        return u"Tool 用户操作层；负责 UI、Selection 和调用底层能力。"

    if relative_path.startswith("ui/"):
        return u"UI 公共层；负责可复用界面组件，不承载 Rig 算法。"

    if relative_path.startswith("app/"):
        return u"应用入口层；负责主工具箱、窗口生命周期和工具调度。"

    return u"MuziTools 包级入口、配置或 API 分类页面。"


# =============================================================================
# Markdown Layout
# =============================================================================

def replace_overview(markdown_text, summary, position):
    u"""把页面概览统一替换为简短的“用途 / 模块定位”。"""
    start_marker = "## 概览"
    end_marker = "## 常用任务"

    start_index = markdown_text.find(
        start_marker
    )
    end_index = markdown_text.find(
        end_marker
    )

    if start_index < 0:
        return markdown_text

    if end_index < 0:
        return markdown_text

    if end_index <= start_index:
        return markdown_text

    overview_lines = [
        "## 概览",
        "",
        "**用途**",
        "",
        summary,
        "",
        "**模块定位**",
        "",
        position,
        "",
    ]
    overview_text = "\n".join(
        overview_lines
    )

    return (
        markdown_text[:start_index]
        + overview_text
        + markdown_text[end_index:]
    )


def add_callable_purpose_labels(markdown_text):
    u"""在每一个 Function / Method 标题后的功能摘要前插入“作用”。"""
    lines = markdown_text.splitlines()
    result_lines = []
    changed_count = 0
    line_index = 0

    while line_index < len(lines):
        line = lines[line_index]
        result_lines.append(
            line
        )

        if not CALLABLE_HEADING_PATTERN.match(line):
            line_index += 1
            continue

        next_index = line_index + 1

        while next_index < len(lines):
            if lines[next_index].strip():
                break

            result_lines.append(
                lines[next_index]
            )
            next_index += 1

        if next_index >= len(lines):
            line_index = next_index
            continue

        if lines[next_index].strip() == "**作用**":
            line_index = next_index
            continue

        result_lines.append(
            "**作用**"
        )
        result_lines.append("")
        changed_count += 1
        line_index = next_index

    refined_text = "\n".join(
        result_lines
    )

    if markdown_text.endswith("\n"):
        refined_text += "\n"

    return refined_text, changed_count


# =============================================================================
# Main
# =============================================================================

def refine_reference_docs(project_root=None):
    u"""整理全部真实生成 API 页面的概览与 Callable“作用”区块。"""
    if project_root is None:
        project_root = get_project_root()

    markdown_files = iter_generated_reference_files(
        project_root
    )

    if not markdown_files:
        raise RuntimeError(
            u"没有找到自动生成 API 页面，请先执行 generate_mkdocs_reference.py。"
        )

    changed_pages = 0
    callable_purpose_labels = 0

    for markdown_path in markdown_files:
        with open(
                markdown_path,
                "r",
                encoding="utf-8"
        ) as file_object:
            markdown_text = file_object.read()

        source_path = get_source_path_from_reference(
            project_root,
            markdown_path
        )
        summary = build_summary_from_source(
            source_path
        )

        if not summary:
            summary = extract_summary_from_overview(
                markdown_text
            )

        position = build_module_position(
            markdown_path,
            project_root
        )

        refined_text = replace_overview(
            markdown_text,
            summary,
            position
        )
        refined_text, purpose_count = add_callable_purpose_labels(
            refined_text
        )

        callable_purpose_labels += purpose_count

        if refined_text == markdown_text:
            continue

        with open(
                markdown_path,
                "w",
                encoding="utf-8",
                newline="\n"
        ) as file_object:
            file_object.write(
                refined_text
            )

        changed_pages += 1

    print(
        u"Generated API pages scanned: {}".format(
            len(markdown_files)
        )
    )
    print(
        u"Refined API pages:          {}".format(
            changed_pages
        )
    )
    print(
        u"Added callable purposes:    {}".format(
            callable_purpose_labels
        )
    )

    return {
        "scanned_pages": len(markdown_files),
        "changed_pages": changed_pages,
        "callable_purpose_labels": callable_purpose_labels,
    }


if __name__ == "__main__":
    refine_reference_docs()
