# coding=utf-8
u"""
MkDocs Reference Generator
==========================

MuziTools 的静态 API 文档生成器。

模块职责
--------
这个脚本使用 Python 标准库 ``ast`` 直接读取源码，不 import Maya 模块，
因此可以在普通 Python、GitHub Actions 或本地文档环境中运行。

当前公开方法
------------
    get_project_root()
        获取仓库根目录。

    get_docs_root(project_root)
        获取 docs 目录。

    iter_source_files(project_root)
        扫描 core / tools / systems 中的正式 Python 模块。

    source_path_to_module_name(project_root, source_path)
        将源码路径转换成真实 Python Import Path。

    read_source_text(source_path)
        读取 UTF-8 Python 源码。

    get_first_paragraph(docstring)
        从 Docstring 中取得第一段功能摘要。

    get_node_doc_summary(node)
        获取函数 / 类 Docstring 第一段摘要。

    format_ast_value(node)
        将 AST 默认值或 Annotation 转成可读字符串。

    format_function_signature(function_node)
        从 AST FunctionDef 生成函数签名。

    collect_class_api(class_node)
        收集一个公开类及其公开方法。

    collect_module_info(project_root, source_path)
        解析一个 Python 模块的 Docstring、函数、类和 API 信息。

    build_usage_scenarios(module_info)
        根据模块所属层级和名称生成第一版“使用场景”。

    build_example(module_info)
        根据模块类型生成安全的第一版 Import / main() 示例。

    build_module_markdown(module_info)
        生成单模块“功能 + 使用场景 + API + 示例”Markdown。

    write_text_file(file_path, content)
        写入 UTF-8 文本文档，并自动创建父目录。

    build_reference_index(title, description, module_items, docs_root)
        生成 Core / Tools / Systems 分类索引。

    clean_generated_reference(reference_root)
        删除旧的自动生成模块页，避免删除手写说明页。

    generate_reference_docs(project_root=None)
        扫描正式源码并生成全部第一版 API Reference。

    main()
        命令行入口。

生成范围
--------
    core/**/*.py
    tools/**/*.py
    systems/**/*.py

默认跳过
--------
    __init__.py
    __pycache__
    私有文件（文件名以 _ 开头）
    legacy_reference/
    tests/

生成页面结构
------------
每一个正式模块会生成：

    # 模块 Import Path
    ## 功能
    ## 使用场景
    ## API
    ## 示例
    ## 源码位置

设计原则
--------
1. 不 import Maya，避免 ``maya.cmds`` 导致在线构建失败；
2. 只依赖 Python 标准库，Maya 2023 自带 Python 也可以运行；
3. 自动文档只是第一版骨架，复杂 Rig Workflow 仍建议补手写说明；
4. 生成文件顶部带 AUTO-GENERATED 标记，避免误把自动页当手写源码；
5. ``docs/reference/*/index.md`` 同样由生成器维护，MkDocs Nav 保持稳定。
"""

from __future__ import print_function

import ast
import os
import shutil


# =============================================================================
# 配置
# =============================================================================

# 只扫描正式运行架构。
source_roots = [
    "core",
    "tools",
    "systems",
]

# 自动生成页面头部标记。
generated_marker = "<!-- AUTO-GENERATED BY scripts/generate_mkdocs_reference.py -->"


# =============================================================================
# Project Path
# =============================================================================

def get_project_root():
    """返回当前脚本所在 MuziTools 仓库的根目录。"""
    # 步骤 1：取得 scripts/ 目录。
    script_directory = os.path.dirname(
        os.path.abspath(__file__)
    )

    # 步骤 2：scripts 的父目录就是仓库根目录。
    project_root = os.path.dirname(script_directory)
    return project_root


def get_docs_root(project_root):
    """返回项目 docs 目录绝对路径。"""
    return os.path.join(
        project_root,
        "docs"
    )


# =============================================================================
# Source Scan
# =============================================================================

def iter_source_files(project_root):
    """
    扫描正式 ``core / tools / systems`` 中的 Python 模块。

    Returns:
        list: 排序后的 Python 文件绝对路径。
    """
    source_files = []

    # -------------------------------------------------------------------------
    # 步骤 1：逐个正式源码根目录扫描。
    # -------------------------------------------------------------------------
    for source_root_name in source_roots:
        source_root = os.path.join(
            project_root,
            source_root_name
        )

        if not os.path.isdir(source_root):
            continue

        # ---------------------------------------------------------------------
        # 步骤 2：递归寻找 Python 文件。
        # ---------------------------------------------------------------------
        for root_directory, folder_names, file_names in os.walk(source_root):
            # 不扫描 __pycache__。
            if "__pycache__" in folder_names:
                folder_names.remove("__pycache__")

            for file_name in file_names:
                if not file_name.endswith(".py"):
                    continue

                # __init__.py 主要负责包入口，不单独生成模块页。
                if file_name == "__init__.py":
                    continue

                # 以下划线开头的内部文件默认不作为公开模块文档。
                if file_name.startswith("_"):
                    continue

                source_path = os.path.join(
                    root_directory,
                    file_name
                )
                source_files.append(source_path)

    # -------------------------------------------------------------------------
    # 步骤 3：排序，保证每次生成结果稳定。
    # -------------------------------------------------------------------------
    source_files.sort()
    return source_files


def source_path_to_module_name(project_root, source_path):
    """
    将源码路径转换成真实 Python Import Path。

    Example:
        core/animation_utils.py
            -> muziToolset.core.animation_utils
    """
    # 步骤 1：取得相对仓库路径。
    relative_path = os.path.relpath(
        source_path,
        project_root
    )

    # 步骤 2：去掉 .py，并把路径分隔符换成点号。
    module_path = os.path.splitext(relative_path)[0]
    module_path = module_path.replace("\\", ".")
    module_path = module_path.replace("/", ".")

    # 步骤 3：正式包名固定为 muziToolset。
    return "muziToolset." + module_path


def read_source_text(source_path):
    """读取 UTF-8 Python 源码。"""
    with open(source_path, "r", encoding="utf-8") as file_object:
        return file_object.read()


# =============================================================================
# Docstring / AST Helper
# =============================================================================

def get_first_paragraph(docstring):
    """从 Docstring 中提取第一段非空文本作为功能摘要。"""
    if not docstring:
        return "当前源码没有模块说明，建议后续补充详细 Docstring。"

    lines = docstring.strip().splitlines()
    paragraph_lines = []

    for line in lines:
        stripped_line = line.strip()

        if not stripped_line:
            if paragraph_lines:
                break
            continue

        # 常见标题下划线不作为摘要正文。
        if set(stripped_line) == set("="):
            continue
        if set(stripped_line) == set("-"):
            continue

        paragraph_lines.append(stripped_line)

    if not paragraph_lines:
        return "当前源码没有可提取的模块摘要。"

    return " ".join(paragraph_lines)


def get_node_doc_summary(node):
    """取得函数或类 Docstring 的第一段摘要。"""
    docstring = ast.get_docstring(node)
    return get_first_paragraph(docstring)


def format_ast_value(node):
    """将 AST 默认值 / Annotation 转成可读源码字符串。"""
    if node is None:
        return ""

    # Python 3.9+ 提供 ast.unparse，Maya 2023 可以使用。
    try:
        return ast.unparse(node)
    except Exception:
        return "..."


def format_function_signature(function_node):
    """
    根据 AST FunctionDef / AsyncFunctionDef 生成可读函数签名。

    这里不执行源码，因此即使函数参数默认值依赖 Maya，也不会产生副作用。
    """
    arguments = function_node.args
    positional_arguments = []

    # -------------------------------------------------------------------------
    # 步骤 1：计算普通参数与默认值的对应关系。
    # -------------------------------------------------------------------------
    all_positional = []

    for argument in arguments.posonlyargs:
        all_positional.append(argument)

    for argument in arguments.args:
        all_positional.append(argument)

    default_count = len(arguments.defaults)
    first_default_index = len(all_positional) - default_count

    for argument_index, argument in enumerate(all_positional):
        argument_text = argument.arg

        if argument.annotation is not None:
            argument_text += ": " + format_ast_value(argument.annotation)

        if argument_index >= first_default_index:
            default_index = argument_index - first_default_index
            default_value = arguments.defaults[default_index]
            argument_text += "=" + format_ast_value(default_value)

        positional_arguments.append(argument_text)

    # -------------------------------------------------------------------------
    # 步骤 2：处理 *args。
    # -------------------------------------------------------------------------
    if arguments.vararg is not None:
        vararg_text = "*" + arguments.vararg.arg

        if arguments.vararg.annotation is not None:
            vararg_text += ": " + format_ast_value(arguments.vararg.annotation)

        positional_arguments.append(vararg_text)
    elif arguments.kwonlyargs:
        # 没有 *args 但有 Keyword Only 参数，需要插入单独的 *。
        positional_arguments.append("*")

    # -------------------------------------------------------------------------
    # 步骤 3：处理 Keyword Only 参数。
    # -------------------------------------------------------------------------
    for keyword_index, argument in enumerate(arguments.kwonlyargs):
        argument_text = argument.arg

        if argument.annotation is not None:
            argument_text += ": " + format_ast_value(argument.annotation)

        default_value = arguments.kw_defaults[keyword_index]

        if default_value is not None:
            argument_text += "=" + format_ast_value(default_value)

        positional_arguments.append(argument_text)

    # -------------------------------------------------------------------------
    # 步骤 4：处理 **kwargs。
    # -------------------------------------------------------------------------
    if arguments.kwarg is not None:
        kwarg_text = "**" + arguments.kwarg.arg

        if arguments.kwarg.annotation is not None:
            kwarg_text += ": " + format_ast_value(arguments.kwarg.annotation)

        positional_arguments.append(kwarg_text)

    signature = "{}({})".format(
        function_node.name,
        ", ".join(positional_arguments)
    )

    if function_node.returns is not None:
        signature += " -> " + format_ast_value(function_node.returns)

    return signature


def collect_class_api(class_node):
    """
    收集一个公开类及其公开方法。

    Returns:
        dict: class_name / summary / methods。
    """
    methods = []

    for child_node in class_node.body:
        if not isinstance(child_node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue

        # __init__ 对理解类构造很重要，因此保留；其它私有方法不进入第一版 API。
        if child_node.name.startswith("_") and child_node.name != "__init__":
            continue

        method_info = {
            "name": child_node.name,
            "signature": format_function_signature(child_node),
            "summary": get_node_doc_summary(child_node),
        }
        methods.append(method_info)

    return {
        "name": class_node.name,
        "summary": get_node_doc_summary(class_node),
        "methods": methods,
    }


def collect_module_info(project_root, source_path):
    """
    解析一个 Python 模块并收集文档需要的信息。

    Returns:
        dict: 模块路径、Docstring、公开函数、公开类等。
    """
    # 步骤 1：读取源码，并使用 AST 解析。
    source_text = read_source_text(source_path)
    module_tree = ast.parse(
        source_text,
        filename=source_path
    )

    # 步骤 2：准备模块基础信息。
    relative_path = os.path.relpath(
        source_path,
        project_root
    ).replace("\\", "/")

    path_parts = relative_path.split("/")
    root_name = path_parts[0]

    module_info = {
        "source_path": source_path,
        "relative_path": relative_path,
        "root_name": root_name,
        "module_name": source_path_to_module_name(
            project_root,
            source_path
        ),
        "module_docstring": ast.get_docstring(module_tree) or "",
        "functions": [],
        "classes": [],
    }

    # 步骤 3：只收集模块顶层公开 Function / Class。
    for node in module_tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if node.name.startswith("_"):
                continue

            function_info = {
                "name": node.name,
                "signature": format_function_signature(node),
                "summary": get_node_doc_summary(node),
            }
            module_info["functions"].append(function_info)

        elif isinstance(node, ast.ClassDef):
            if node.name.startswith("_"):
                continue

            module_info["classes"].append(
                collect_class_api(node)
            )

    return module_info


# =============================================================================
# 文档内容生成
# =============================================================================

def build_usage_scenarios(module_info):
    """根据模块位置和名称生成第一版“使用场景”文本。"""
    module_name = module_info["module_name"].lower()
    root_name = module_info["root_name"]
    scenarios = []

    # -------------------------------------------------------------------------
    # 步骤 1：按架构层级给出通用使用场景。
    # -------------------------------------------------------------------------
    if root_name == "core":
        scenarios.append("需要在多个 Tool / System 中复用同一套 Maya 底层能力时。")
        scenarios.append("希望场景逻辑与 PySide UI 分离，并且可以独立做 Smoke Test 时。")

    elif root_name == "tools":
        scenarios.append("用户需要从 MuziTools 主工具箱直接打开一个独立小工具时。")
        scenarios.append("需要收集 Selection / UI 参数，再调用 Core 或 System 完成场景操作时。")

    elif root_name == "systems":
        scenarios.append("需要构建可被多个 Tool 复用的完整 Rig Workflow / Builder 时。")
        scenarios.append("一个功能已经超出单个 Core 函数，需要组织多个 Maya 节点和步骤时。")

    # -------------------------------------------------------------------------
    # 步骤 2：根据模块名称补一条更具体的场景说明。
    # -------------------------------------------------------------------------
    keyword_scenarios = [
        ("animation", "处理动画关键帧、控制器 Reset 或动画数据交换时。"),
        ("attr", "创建、查询、锁定或管理 Maya Attribute 时。"),
        ("blendshape", "创建或管理 BlendShape Target / Alias 时。"),
        ("connection", "建立、复制或断开 Maya DG Plug 连接时。"),
        ("constraint", "创建或清理 Maya Constraint Node 时。"),
        ("control", "创建或编辑绑定控制器及 Controller Shape 时。"),
        ("curve", "沿 NURBS Curve 采样、附着或生成 Rig 数据时。"),
        ("file", "读写 JSON、处理路径或扫描文件目录时。"),
        ("hierarchy", "创建或整理 Maya DAG 层级时。"),
        ("joint", "创建、排列或处理绑定 Joint 时。"),
        ("matrix", "使用 Matrix / offsetParentMatrix 构建无 Constraint 驱动时。"),
        ("mesh", "复制或查询 Mesh Geometry 时。"),
        ("model_check", "绑定前检查模型命名、Transform 或拓扑基础状态时。"),
        ("name", "生成、解析或批量调整 MuziTools 命名时。"),
        ("rename", "根据规则批量重命名 Maya 节点时。"),
        ("scene_clean", "发布 / 交付前清理 Maya Scene 时。"),
        ("scene", "处理 Scene、Selection、Set、Reference 或 Scene IO 时。"),
        ("skin", "查找 SkinCluster、复制或导入导出蒙皮权重时。"),
        ("snap", "需要对齐 Transform 或 Component 时。"),
        ("surface", "创建 NURBS Surface、Follicle 或 Surface Attachment 时。"),
        ("transform", "读取 / 设置位置、距离或 World Matrix 时。"),
        ("face", "构建 Face Guide、Eyelid、Lip 或其它面部绑定组件时。"),
        ("skirt", "构建裙摆绑定系统时。"),
        ("controller", "构建标准 Controller 层级或 Parent Space Blend 时。"),
    ]

    for keyword, description in keyword_scenarios:
        if keyword in module_name:
            if description not in scenarios:
                scenarios.append(description)
            break

    return scenarios


def build_example(module_info):
    """根据模块类型生成不会擅自修改 Maya Scene 的第一版示例。"""
    module_name = module_info["module_name"]
    root_name = module_info["root_name"]
    short_name = module_name.split(".")[-1]

    lines = []
    lines.append("```python")

    if root_name == "tools":
        # Tool 如果公开 main()，可以给出标准窗口启动示例。
        has_main = False

        for function_info in module_info["functions"]:
            if function_info["name"] == "main":
                has_main = True
                break

        lines.append("from {} import {}".format(
            ".".join(module_name.split(".")[:-1]),
            short_name
        ))
        lines.append("")

        if has_main:
            lines.append("window = {}.main()".format(short_name))
        else:
            lines.append("# 该模块没有公开 main()；请从 MuziTools 主工具箱调用。")

    else:
        lines.append("from {} import {}".format(
            ".".join(module_name.split(".")[:-1]),
            short_name
        ))
        lines.append("")
        lines.append("# 先导入模块，再根据下方 API 传入明确的 Maya 节点 / 参数。")

        if module_info["functions"]:
            first_function = module_info["functions"][0]
            lines.append("# 例如可查看：{}.{}".format(
                short_name,
                first_function["signature"]
            ))
        elif module_info["classes"]:
            first_class = module_info["classes"][0]
            lines.append("# 主要类：{}.{}".format(
                short_name,
                first_class["name"]
            ))

    lines.append("```")
    return "\n".join(lines)


def build_module_markdown(module_info):
    """生成一个模块的第一版 Markdown 文档。"""
    lines = []
    lines.append(generated_marker)
    lines.append("")
    lines.append("# `{}`".format(module_info["module_name"]))
    lines.append("")
    lines.append("> 本页由 `scripts/generate_mkdocs_reference.py` 根据当前源码静态生成。")
    lines.append("")

    # -------------------------------------------------------------------------
    # 功能
    # -------------------------------------------------------------------------
    lines.append("## 功能")
    lines.append("")
    lines.append(get_first_paragraph(module_info["module_docstring"]))
    lines.append("")

    # -------------------------------------------------------------------------
    # 使用场景
    # -------------------------------------------------------------------------
    lines.append("## 使用场景")
    lines.append("")

    scenarios = build_usage_scenarios(module_info)

    for scenario in scenarios:
        lines.append("- " + scenario)

    if not scenarios:
        lines.append("- 作为 MuziTools 正式模块，由对应上层工具或系统调用。")

    lines.append("")

    # -------------------------------------------------------------------------
    # API
    # -------------------------------------------------------------------------
    lines.append("## API")
    lines.append("")

    if module_info["functions"]:
        lines.append("### Functions")
        lines.append("")
        lines.append("| API | 功能 |")
        lines.append("| --- | --- |")

        for function_info in module_info["functions"]:
            signature = function_info["signature"].replace("|", "\\|")
            summary = function_info["summary"].replace("|", "\\|")
            lines.append("| `{}` | {} |".format(signature, summary))

        lines.append("")

    for class_info in module_info["classes"]:
        lines.append("### Class `{}`".format(class_info["name"]))
        lines.append("")
        lines.append(class_info["summary"])
        lines.append("")

        if class_info["methods"]:
            lines.append("| Method | 功能 |")
            lines.append("| --- | --- |")

            for method_info in class_info["methods"]:
                signature = method_info["signature"].replace("|", "\\|")
                summary = method_info["summary"].replace("|", "\\|")
                lines.append("| `{}` | {} |".format(signature, summary))

            lines.append("")

    if not module_info["functions"] and not module_info["classes"]:
        lines.append("当前模块没有检测到公开 Function / Class。")
        lines.append("")

    # -------------------------------------------------------------------------
    # 示例
    # -------------------------------------------------------------------------
    lines.append("## 示例")
    lines.append("")
    lines.append(build_example(module_info))
    lines.append("")

    # -------------------------------------------------------------------------
    # 源码位置
    # -------------------------------------------------------------------------
    lines.append("## 源码位置")
    lines.append("")
    lines.append("`{}`".format(module_info["relative_path"]))
    lines.append("")

    return "\n".join(lines)


# =============================================================================
# File Write / Index
# =============================================================================

def write_text_file(file_path, content):
    """写入 UTF-8 文本，并自动创建父目录。"""
    parent_directory = os.path.dirname(file_path)

    if not os.path.isdir(parent_directory):
        os.makedirs(parent_directory)

    with open(file_path, "w", encoding="utf-8", newline="\n") as file_object:
        file_object.write(content)


def get_output_relative_path(module_info):
    """计算一个源码模块对应的 docs/reference 下输出路径。"""
    relative_source = module_info["relative_path"]
    relative_without_extension = os.path.splitext(relative_source)[0]
    return relative_without_extension + ".md"


def build_reference_index(title, description, module_items, docs_root):
    """生成一个 Reference 分类索引 Markdown。"""
    lines = []
    lines.append(generated_marker)
    lines.append("")
    lines.append("# {}".format(title))
    lines.append("")
    lines.append(description)
    lines.append("")
    lines.append("| 模块 | 源码 |")
    lines.append("| --- | --- |")

    for module_info, output_path in module_items:
        index_directory = os.path.join(
            docs_root,
            "reference",
            module_info["root_name"]
        )

        relative_link = os.path.relpath(
            output_path,
            index_directory
        ).replace("\\", "/")

        lines.append(
            "| [`{}`]({}) | `{}` |".format(
                module_info["module_name"],
                relative_link,
                module_info["relative_path"]
            )
        )

    lines.append("")
    return "\n".join(lines)


def clean_generated_reference(reference_root):
    """
    删除旧自动生成模块页。

    注意：
        这里只删除含 generated_marker 的 .md，避免误删开发者手写文档。
    """
    if not os.path.isdir(reference_root):
        return

    for root_directory, folder_names, file_names in os.walk(reference_root):
        for file_name in file_names:
            if not file_name.endswith(".md"):
                continue

            file_path = os.path.join(
                root_directory,
                file_name
            )

            try:
                with open(file_path, "r", encoding="utf-8") as file_object:
                    first_content = file_object.read(512)
            except OSError:
                continue

            if generated_marker not in first_content:
                continue

            os.remove(file_path)

    # 清理被生成器留下的空目录，但保留 reference 根目录本身。
    for root_directory, folder_names, file_names in os.walk(
            reference_root,
            topdown=False
    ):
        if root_directory == reference_root:
            continue

        if os.listdir(root_directory):
            continue

        shutil.rmtree(root_directory)


def generate_reference_docs(project_root=None):
    """
    扫描正式源码并生成全部 MkDocs API Reference。

    Returns:
        dict: generated_modules / output_files。
    """
    # -------------------------------------------------------------------------
    # 步骤 1：确定项目和文档目录。
    # -------------------------------------------------------------------------
    if project_root is None:
        project_root = get_project_root()

    docs_root = get_docs_root(project_root)
    reference_root = os.path.join(
        docs_root,
        "reference"
    )

    # -------------------------------------------------------------------------
    # 步骤 2：清理上一轮自动生成文件。
    # -------------------------------------------------------------------------
    clean_generated_reference(reference_root)

    # -------------------------------------------------------------------------
    # 步骤 3：扫描并解析全部正式 Python 模块。
    # -------------------------------------------------------------------------
    source_files = iter_source_files(project_root)
    module_infos = []

    for source_path in source_files:
        module_info = collect_module_info(
            project_root,
            source_path
        )
        module_infos.append(module_info)

    output_files = []
    category_items = {
        "core": [],
        "tools": [],
        "systems": [],
    }

    # -------------------------------------------------------------------------
    # 步骤 4：逐模块生成 Markdown 页面。
    # -------------------------------------------------------------------------
    for module_info in module_infos:
        output_relative_path = get_output_relative_path(module_info)
        output_path = os.path.join(
            reference_root,
            output_relative_path
        )

        markdown_content = build_module_markdown(module_info)
        write_text_file(
            output_path,
            markdown_content
        )

        output_files.append(output_path)
        category_items[module_info["root_name"]].append(
            (module_info, output_path)
        )

    # -------------------------------------------------------------------------
    # 步骤 5：为三个正式层级生成分类 Index。
    # -------------------------------------------------------------------------
    category_settings = {
        "core": (
            "Core API",
            "Core 是 MuziTools 的 Maya 通用底层能力层，不包含 PySide UI 和完整 Rig Workflow。",
        ),
        "tools": (
            "Tools API",
            "Tools 是用户可以直接打开的小工具，主要负责 UI、Selection 和调用 Core / Systems。",
        ),
        "systems": (
            "Systems API",
            "Systems 是可复用的完整 Rig Builder / Workflow，例如 Controller、Face 和 Body 组件。",
        ),
    }

    for category_name in source_roots:
        title, description = category_settings[category_name]
        index_content = build_reference_index(
            title,
            description,
            category_items[category_name],
            docs_root
        )

        index_path = os.path.join(
            reference_root,
            category_name,
            "index.md"
        )
        write_text_file(
            index_path,
            index_content
        )
        output_files.append(index_path)

    return {
        "generated_modules": len(module_infos),
        "output_files": output_files,
    }


# =============================================================================
# Command Line
# =============================================================================

def main():
    """命令行入口：生成全部第一版 Reference 文档并打印结果。"""
    result = generate_reference_docs()

    print("=" * 78)
    print("MuziTools MkDocs Reference Generator")
    print("=" * 78)
    print("Generated modules: {}".format(result["generated_modules"]))
    print("Generated files:   {}".format(len(result["output_files"])))
    print("=" * 78)

    return result


if __name__ == "__main__":
    main()
