# coding=utf-8
u"""
MkDocs Reference Generator
==========================

MuziTools 静态 API 文档生成器。

设计目标
--------
1. 不 import Maya / PySide 模块，只使用 Python AST；
2. 每一个正式运行时 Python 文件都有独立 API 页面；
3. 每一个公开 Function / Class / Method 都生成详细说明；
4. 自动展示 Signature、参数、默认值、返回值、异常、示例和 Notes；
5. 源码 Docstring 是文档的第一事实来源，生成器只做结构化展示；
6. 没有写完整 Docstring 时也能从 AST 生成安全的 API 骨架；
7. 文档目录尽量与源码目录一致，便于从文件快速定位到 API；
8. 复杂 Rig Workflow 仍保留手写 User Guide，不把教程和 API Reference 混在一起。

生成范围
--------
正式运行时模块：

    app/**/*.py
    core/**/*.py
    systems/**/*.py
    tools/**/*.py
    ui/**/*.py
    config.py

默认不扫描：

    legacy_reference/
    tests/
    scripts/
    __pycache__/

说明
----
``__init__.py`` 也属于正式 Python 文件，因此会生成 ``package.md``，
但不会与分类 ``index.md`` 冲突。

文档风格
--------
文档信息架构参考任务导向的用户手册思路：

    概览
    常用任务
    API 一览
    详细 API
    示例
    相关内容

API 页面内部则保持开发者参考所需的完整技术信息。
"""

from __future__ import print_function

import ast
import os
import re
import shutil


# =============================================================================
# 配置
# =============================================================================

# 正式运行时源码根目录。
source_roots = [
    "app",
    "core",
    "systems",
    "tools",
    "ui",
]

# 根目录下仍属于正式运行时 API 的独立模块。
root_module_files = [
    "__init__.py",
    "config.py",
]

# 自动生成页面头部标记。
generated_marker = "<!-- AUTO-GENERATED BY scripts/generate_mkdocs_reference.py -->"

# Docstring 支持的章节名称。
section_aliases = {
    "args": "args",
    "arguments": "args",
    "parameters": "args",
    "params": "args",
    "参数": "args",
    "参数说明": "args",

    "returns": "returns",
    "return": "returns",
    "返回": "returns",
    "返回值": "returns",

    "raises": "raises",
    "exceptions": "raises",
    "异常": "raises",
    "异常说明": "raises",

    "example": "examples",
    "examples": "examples",
    "示例": "examples",
    "使用示例": "examples",

    "notes": "notes",
    "note": "notes",
    "注意": "notes",
    "说明": "notes",
    "备注": "notes",

    "usage": "usage",
    "use cases": "usage",
    "使用场景": "usage",
    "适用场景": "usage",
}


# =============================================================================
# Project Path
# =============================================================================

def get_project_root():
    """返回当前脚本所在 MuziTools 仓库根目录。"""
    script_directory = os.path.dirname(
        os.path.abspath(__file__)
    )

    project_root = os.path.dirname(
        script_directory
    )
    return project_root


def get_docs_root(project_root):
    """返回项目 docs 目录绝对路径。"""
    docs_root = os.path.join(
        project_root,
        "docs"
    )
    return docs_root


# =============================================================================
# Source Scan
# =============================================================================

def is_public_python_file(file_name):
    """
    判断一个文件是否属于正式 API 文档范围。

    Args:
        file_name (str):
            Python 文件名称。

    Returns:
        bool:
            可以生成 API 文档时返回 True。
    """
    if not file_name.endswith(".py"):
        return False

    # ``__init__.py`` 是 Package API 的组成部分，需要生成文档。
    if file_name == "__init__.py":
        return True

    # 私有模块不进入公开 API。
    if file_name.startswith("_"):
        return False

    return True


def iter_source_files(project_root):
    """
    扫描正式运行时 Python 模块。

    Args:
        project_root (str):
            MuziTools 仓库根目录。

    Returns:
        list:
            排序后的 Python 文件绝对路径。
    """
    source_files = []

    # -------------------------------------------------------------------------
    # 步骤 1：扫描 app / core / systems / tools / ui。
    # -------------------------------------------------------------------------
    for source_root_name in source_roots:
        source_root = os.path.join(
            project_root,
            source_root_name
        )

        if not os.path.isdir(source_root):
            continue

        for root_directory, folder_names, file_names in os.walk(source_root):
            ignored_folders = [
                "__pycache__",
            ]

            for ignored_folder in ignored_folders:
                if ignored_folder in folder_names:
                    folder_names.remove(
                        ignored_folder
                    )

            for file_name in file_names:
                if not is_public_python_file(file_name):
                    continue

                source_path = os.path.join(
                    root_directory,
                    file_name
                )
                source_files.append(
                    source_path
                )

    # -------------------------------------------------------------------------
    # 步骤 2：补充仓库根目录的正式独立模块。
    # -------------------------------------------------------------------------
    for file_name in root_module_files:
        source_path = os.path.join(
            project_root,
            file_name
        )

        if not os.path.isfile(source_path):
            continue

        source_files.append(
            source_path
        )

    source_files.sort()
    return source_files


def source_path_to_module_name(project_root, source_path):
    """
    将源码路径转换成真实 Python Import Path。

    Example:
        ``core/animation_utils.py``
        -> ``muziToolset.core.animation_utils``
    """
    relative_path = os.path.relpath(
        source_path,
        project_root
    )

    relative_path = relative_path.replace(
        "\\",
        "/"
    )

    if relative_path == "__init__.py":
        return "muziToolset"

    module_path = os.path.splitext(
        relative_path
    )[0]

    if module_path.endswith("/__init__"):
        module_path = module_path[:-len("/__init__")]

    module_path = module_path.replace(
        "/",
        "."
    )

    return "muziToolset." + module_path


def read_source_text(source_path):
    """读取 UTF-8 Python 源码。"""
    with open(
            source_path,
            "r",
            encoding="utf-8"
    ) as file_object:
        return file_object.read()


# =============================================================================
# Docstring Parser
# =============================================================================

def normalize_section_name(text):
    """把 Docstring 章节标题整理成生成器内部标准名称。"""
    if not text:
        return None

    normalized_text = text.strip()
    normalized_text = normalized_text.rstrip(":")
    normalized_text = normalized_text.lower()

    return section_aliases.get(
        normalized_text
    )


def split_docstring_sections(docstring):
    """
    将 Docstring 拆成 Summary / Body / Args / Returns / Raises / Examples 等区域。

    兼容常见 Google Style 和中文章节标题。
    """
    result = {
        "summary": "",
        "body": "",
        "args": "",
        "returns": "",
        "raises": "",
        "examples": "",
        "notes": "",
        "usage": "",
    }

    if not docstring:
        return result

    raw_lines = docstring.expandtabs(4).strip().splitlines()

    current_section = "body"
    section_lines = {
        "body": [],
        "args": [],
        "returns": [],
        "raises": [],
        "examples": [],
        "notes": [],
        "usage": [],
    }

    # -------------------------------------------------------------------------
    # 步骤 1：根据章节标题分组。
    # -------------------------------------------------------------------------
    for line in raw_lines:
        stripped_line = line.strip()
        section_name = normalize_section_name(
            stripped_line
        )

        if section_name:
            current_section = section_name
            continue

        section_lines[current_section].append(
            line.rstrip()
        )

    # -------------------------------------------------------------------------
    # 步骤 2：Body 第一段作为 Summary，其余保留为详细说明。
    # -------------------------------------------------------------------------
    body_lines = section_lines["body"]
    summary_lines = []
    remaining_lines = []
    summary_finished = False

    for line in body_lines:
        stripped_line = line.strip()

        if not stripped_line:
            if summary_lines:
                summary_finished = True
            continue

        # 常见标题下划线不进入摘要。
        if stripped_line:
            character_set = set(stripped_line)

            if character_set == set("="):
                continue

            if character_set == set("-"):
                continue

        if not summary_finished:
            summary_lines.append(
                stripped_line
            )
        else:
            remaining_lines.append(
                line
            )

    result["summary"] = " ".join(
        summary_lines
    ).strip()

    result["body"] = "\n".join(
        remaining_lines
    ).strip()

    for section_name in [
        "args",
        "returns",
        "raises",
        "examples",
        "notes",
        "usage",
    ]:
        result[section_name] = "\n".join(
            section_lines[section_name]
        ).strip()

    return result


def get_first_paragraph(docstring):
    """从 Docstring 中取得第一段功能摘要。"""
    sections = split_docstring_sections(
        docstring
    )

    if sections["summary"]:
        return sections["summary"]

    return "当前源码没有可提取的功能摘要。"


def parse_argument_descriptions(args_text):
    """
    解析 Google Style ``Args`` 章节。

    支持：

        node (str):
            Maya 节点名称。

        node:
            Maya 节点名称。
    """
    descriptions = {}

    if not args_text:
        return descriptions

    lines = args_text.splitlines()
    current_name = None
    current_description = []

    argument_pattern = re.compile(
        r"^\s*([*]{0,2}[A-Za-z_][A-Za-z0-9_]*)"
        r"(?:\s*\(([^)]*)\))?\s*:\s*(.*)$"
    )

    current_type = ""

    def save_current_argument():
        """把正在解析的参数保存到结果字典。"""
        if current_name is None:
            return

        description_text = " ".join(
            current_description
        ).strip()

        descriptions[current_name] = {
            "type": current_type or "",
            "description": description_text,
        }

    for line in lines:
        match = argument_pattern.match(
            line
        )

        if match:
            save_current_argument()

            current_name = match.group(1)
            current_name = current_name.lstrip("*")
            current_type = match.group(2) or ""

            current_description = []

            inline_description = match.group(3).strip()

            if inline_description:
                current_description.append(
                    inline_description
                )

            continue

        stripped_line = line.strip()

        if current_name is None:
            continue

        if not stripped_line:
            continue

        current_description.append(
            stripped_line
        )

    save_current_argument()
    return descriptions


def parse_raises(raises_text):
    """解析 Raises / 异常章节。"""
    result = []

    if not raises_text:
        return result

    lines = raises_text.splitlines()
    current_exception = None
    current_description = []

    exception_pattern = re.compile(
        r"^\s*([A-Za-z_][A-Za-z0-9_.]*)\s*:\s*(.*)$"
    )

    def save_current_exception():
        """保存当前异常说明。"""
        if current_exception is None:
            return

        result.append({
            "type": current_exception,
            "description": " ".join(
                current_description
            ).strip(),
        })

    for line in lines:
        match = exception_pattern.match(
            line
        )

        if match:
            save_current_exception()

            current_exception = match.group(1)
            current_description = []

            inline_description = match.group(2).strip()

            if inline_description:
                current_description.append(
                    inline_description
                )

            continue

        stripped_line = line.strip()

        if current_exception is None:
            continue

        if not stripped_line:
            continue

        current_description.append(
            stripped_line
        )

    save_current_exception()
    return result


# =============================================================================
# AST Helper
# =============================================================================

def format_ast_value(node):
    """把 AST 默认值 / Annotation 转成可读源码字符串。"""
    if node is None:
        return ""

    try:
        return ast.unparse(node)
    except Exception:
        return "..."


def get_function_parameters(function_node):
    """
    收集函数参数信息。

    Returns:
        list:
            每个元素都包含 name / type / default / required / kind。
    """
    parameters = []
    arguments = function_node.args

    all_positional = []

    for argument in arguments.posonlyargs:
        all_positional.append(
            ("positional_only", argument)
        )

    for argument in arguments.args:
        all_positional.append(
            ("positional", argument)
        )

    default_count = len(
        arguments.defaults
    )
    first_default_index = len(all_positional) - default_count

    for argument_index, parameter_data in enumerate(all_positional):
        parameter_kind = parameter_data[0]
        argument = parameter_data[1]

        default_text = ""
        required = True

        if argument_index >= first_default_index:
            default_index = argument_index - first_default_index
            default_node = arguments.defaults[
                default_index
            ]
            default_text = format_ast_value(
                default_node
            )
            required = False

        annotation_text = format_ast_value(
            argument.annotation
        )

        parameters.append({
            "name": argument.arg,
            "type": annotation_text,
            "default": default_text,
            "required": required,
            "kind": parameter_kind,
        })

    if arguments.vararg is not None:
        parameters.append({
            "name": arguments.vararg.arg,
            "type": format_ast_value(
                arguments.vararg.annotation
            ),
            "default": "",
            "required": False,
            "kind": "vararg",
        })

    for keyword_index, argument in enumerate(arguments.kwonlyargs):
        default_node = arguments.kw_defaults[
            keyword_index
        ]

        default_text = ""
        required = True

        if default_node is not None:
            default_text = format_ast_value(
                default_node
            )
            required = False

        parameters.append({
            "name": argument.arg,
            "type": format_ast_value(
                argument.annotation
            ),
            "default": default_text,
            "required": required,
            "kind": "keyword_only",
        })

    if arguments.kwarg is not None:
        parameters.append({
            "name": arguments.kwarg.arg,
            "type": format_ast_value(
                arguments.kwarg.annotation
            ),
            "default": "",
            "required": False,
            "kind": "kwarg",
        })

    return parameters


def format_function_signature(function_node):
    """根据 AST FunctionDef 生成函数签名。"""
    parameters = get_function_parameters(
        function_node
    )
    parameter_texts = []

    has_vararg = False
    keyword_only_started = False

    for parameter in parameters:
        name = parameter["name"]
        parameter_type = parameter["type"]
        default_text = parameter["default"]
        parameter_kind = parameter["kind"]

        if parameter_kind == "vararg":
            text = "*" + name
            has_vararg = True

        elif parameter_kind == "kwarg":
            text = "**" + name

        else:
            if parameter_kind == "keyword_only":
                if not has_vararg and not keyword_only_started:
                    parameter_texts.append(
                        "*"
                    )
                    keyword_only_started = True

            text = name

        if parameter_type:
            text += ": " + parameter_type

        if default_text:
            text += "=" + default_text

        parameter_texts.append(
            text
        )

    signature = "{}({})".format(
        function_node.name,
        ", ".join(parameter_texts)
    )

    if function_node.returns is not None:
        signature += " -> " + format_ast_value(
            function_node.returns
        )

    return signature


def build_callable_info(function_node):
    """把 Function / Method AST 节点整理成文档数据。"""
    docstring = ast.get_docstring(
        function_node
    ) or ""

    sections = split_docstring_sections(
        docstring
    )

    argument_descriptions = parse_argument_descriptions(
        sections["args"]
    )

    parameters = get_function_parameters(
        function_node
    )

    for parameter in parameters:
        parameter_name = parameter["name"]

        description_info = argument_descriptions.get(
            parameter_name
        )

        parameter["description"] = ""

        if description_info:
            if description_info["type"]:
                parameter["doc_type"] = description_info["type"]
            else:
                parameter["doc_type"] = ""

            parameter["description"] = description_info[
                "description"
            ]
        else:
            parameter["doc_type"] = ""

    return {
        "name": function_node.name,
        "signature": format_function_signature(
            function_node
        ),
        "docstring": docstring,
        "summary": sections["summary"],
        "body": sections["body"],
        "parameters": parameters,
        "returns": sections["returns"],
        "raises": parse_raises(
            sections["raises"]
        ),
        "examples": sections["examples"],
        "notes": sections["notes"],
        "usage": sections["usage"],
        "return_annotation": format_ast_value(
            function_node.returns
        ),
        "lineno": getattr(
            function_node,
            "lineno",
            None
        ),
    }


def collect_class_api(class_node):
    """收集公开类、构造函数和公开方法。"""
    methods = []
    constructor = None

    for child_node in class_node.body:
        if not isinstance(
                child_node,
                (ast.FunctionDef, ast.AsyncFunctionDef)
        ):
            continue

        if child_node.name == "__init__":
            constructor = build_callable_info(
                child_node
            )
            continue

        if child_node.name.startswith("_"):
            continue

        method_info = build_callable_info(
            child_node
        )
        methods.append(
            method_info
        )

    class_docstring = ast.get_docstring(
        class_node
    ) or ""

    class_sections = split_docstring_sections(
        class_docstring
    )

    return {
        "name": class_node.name,
        "docstring": class_docstring,
        "summary": class_sections["summary"],
        "body": class_sections["body"],
        "notes": class_sections["notes"],
        "usage": class_sections["usage"],
        "constructor": constructor,
        "methods": methods,
        "lineno": getattr(
            class_node,
            "lineno",
            None
        ),
    }


def collect_module_info(project_root, source_path):
    """解析一个 Python 文件，并收集模块级 API 信息。"""
    source_text = read_source_text(
        source_path
    )

    module_tree = ast.parse(
        source_text,
        filename=source_path
    )

    relative_path = os.path.relpath(
        source_path,
        project_root
    ).replace(
        "\\",
        "/"
    )

    path_parts = relative_path.split(
        "/"
    )

    if len(path_parts) == 1:
        root_name = "package"
    else:
        root_name = path_parts[0]

    module_docstring = ast.get_docstring(
        module_tree
    ) or ""

    module_sections = split_docstring_sections(
        module_docstring
    )

    module_info = {
        "source_path": source_path,
        "relative_path": relative_path,
        "root_name": root_name,
        "module_name": source_path_to_module_name(
            project_root,
            source_path
        ),
        "module_docstring": module_docstring,
        "summary": module_sections["summary"],
        "body": module_sections["body"],
        "notes": module_sections["notes"],
        "usage": module_sections["usage"],
        "functions": [],
        "classes": [],
        "constants": [],
    }

    # -------------------------------------------------------------------------
    # 公开顶层 Function / Class。
    # -------------------------------------------------------------------------
    for node in module_tree.body:
        if isinstance(
                node,
                (ast.FunctionDef, ast.AsyncFunctionDef)
        ):
            if node.name.startswith("_"):
                continue

            module_info["functions"].append(
                build_callable_info(
                    node
                )
            )

        elif isinstance(node, ast.ClassDef):
            if node.name.startswith("_"):
                continue

            module_info["classes"].append(
                collect_class_api(
                    node
                )
            )

        elif isinstance(node, (ast.Assign, ast.AnnAssign)):
            constant_name = None
            constant_value = ""

            if isinstance(node, ast.Assign):
                if len(node.targets) == 1:
                    target = node.targets[0]

                    if isinstance(target, ast.Name):
                        constant_name = target.id

                constant_value = format_ast_value(
                    node.value
                )

            else:
                if isinstance(node.target, ast.Name):
                    constant_name = node.target.id

                constant_value = format_ast_value(
                    node.value
                )

            if not constant_name:
                continue

            if constant_name.startswith("_"):
                continue

            # 只把全大写或明显配置表暴露到模块常量区域。
            if constant_name.isupper():
                module_info["constants"].append({
                    "name": constant_name,
                    "value": constant_value,
                })

    return module_info


# =============================================================================
# 文档内容 Helper
# =============================================================================

def escape_table_text(text):
    """转义 Markdown Table 中可能破坏表格的字符。"""
    if text is None:
        return ""

    result = str(text)
    result = result.replace(
        "|",
        "\\|"
    )
    result = result.replace(
        "\n",
        " "
    )
    return result


def build_usage_scenarios(module_info):
    """根据模块位置和命名生成模块级常用使用场景。"""
    if module_info["usage"]:
        usage_lines = []

        for line in module_info["usage"].splitlines():
            stripped_line = line.strip()

            if not stripped_line:
                continue

            usage_lines.append(
                stripped_line.lstrip("-* ")
            )

        if usage_lines:
            return usage_lines

    module_name = module_info["module_name"].lower()
    root_name = module_info["root_name"]
    scenarios = []

    if root_name == "core":
        scenarios.append(
            "在多个 Tool / System 中复用同一套 Maya 底层能力时。"
        )
        scenarios.append(
            "希望业务逻辑与 UI 分离，并保持可测试、可组合时。"
        )

    elif root_name == "tools":
        scenarios.append(
            "绑定师需要直接打开一个独立 Maya 小工具完成具体操作时。"
        )
        scenarios.append(
            "UI 负责收集 Selection / 参数，再调用 Core 或 Systems 时。"
        )

    elif root_name == "systems":
        scenarios.append(
            "构建可以被多个工具复用的完整 Rig Component / Workflow 时。"
        )
        scenarios.append(
            "需要稳定输入、输出和可重复 Build 行为时。"
        )

    elif root_name == "app":
        scenarios.append(
            "启动 MuziTools 主程序、工具箱或管理顶层窗口生命周期时。"
        )

    elif root_name == "ui":
        scenarios.append(
            "多个工具需要复用统一的 PySide 窗口、控件或主题样式时。"
        )

    else:
        scenarios.append(
            "作为 MuziTools 包级配置或运行时公共入口使用。"
        )

    keyword_scenarios = [
        (
            "face",
            "构建或管理 Face Setup、Guide、Eyelid、Lip 等面部绑定流程时。"
        ),
        (
            "controller",
            "创建标准 Controller、FK 控制器或空间切换时。"
        ),
        (
            "joint",
            "创建、重采样、整理或查询 Jnt 时。"
        ),
        (
            "skin",
            "创建 SkinCluster、处理权重或绑定关系时。"
        ),
        (
            "blendshape",
            "创建、编辑或查询 BlendShape / 修型目标时。"
        ),
        (
            "curve",
            "创建、查询或使用 Curve 驱动绑定节点时。"
        ),
        (
            "matrix",
            "使用 Matrix 节点构建稳定的约束或空间关系时。"
        ),
        (
            "clean",
            "检查或清理 Maya 场景、模型和绑定层级时。"
        ),
        (
            "rename",
            "批量整理节点命名时。"
        ),
    ]

    for keyword, description in keyword_scenarios:
        if keyword not in module_name:
            continue

        if description not in scenarios:
            scenarios.append(
                description
            )

        break

    return scenarios


def build_import_example(module_info):
    """生成模块 Import 示例。"""
    module_name = module_info["module_name"]

    if module_name == "muziToolset":
        return "import muziToolset"

    module_parts = module_name.split(".")
    short_name = module_parts[-1]
    parent_module = ".".join(
        module_parts[:-1]
    )

    return "from {} import {}".format(
        parent_module,
        short_name
    )


def build_parameter_placeholder(parameter):
    """根据参数元数据生成安全的示例占位值。"""
    parameter_name = parameter["name"].lower()
    parameter_type = (
        parameter["type"]
        or parameter["doc_type"]
        or ""
    ).lower()

    if parameter["default"]:
        return parameter["default"]

    if "bool" in parameter_type:
        return "True"

    if "int" in parameter_type:
        return "1"

    if "float" in parameter_type:
        return "1.0"

    if "list" in parameter_type or "tuple" in parameter_type:
        return "[]"

    if "dict" in parameter_type:
        return "{}"

    string_tokens = [
        "name",
        "node",
        "object",
        "target",
        "source",
        "parent",
        "child",
        "joint",
        "curve",
        "mesh",
        "model",
        "control",
        "ctrl",
        "attr",
        "path",
        "side",
    ]

    for token in string_tokens:
        if token in parameter_name:
            return '"{}"'.format(
                parameter["name"]
            )

    return "..."


def get_required_parameters(parameters, include_self=False):
    """返回调用示例需要展示的必要参数。"""
    result = []

    for parameter in parameters:
        parameter_name = parameter["name"]

        if not include_self:
            if parameter_name in ["self", "cls"]:
                continue

        if parameter["kind"] in ["vararg", "kwarg"]:
            continue

        if not parameter["required"]:
            continue

        result.append(
            parameter
        )

    return result


def build_callable_example(
        module_info,
        callable_info,
        class_info=None
):
    """为 Function / Method 生成最小安全调用示例。"""
    lines = []
    lines.append("```python")
    lines.append(
        build_import_example(
            module_info
        )
    )
    lines.append("")

    module_short_name = module_info[
        "module_name"
    ].split(".")[-1]

    required_parameters = get_required_parameters(
        callable_info["parameters"]
    )

    if class_info is not None:
        if callable_info["name"] == "__init__":
            class_name = class_info["name"]

            if required_parameters:
                lines.append(
                    "instance = {}.{}(".format(
                        module_short_name,
                        class_name
                    )
                )

                for parameter in required_parameters:
                    lines.append(
                        "    {}={}".format(
                            parameter["name"],
                            build_parameter_placeholder(
                                parameter
                            )
                        ) + ","
                    )

                lines.append(")")
            else:
                lines.append(
                    "instance = {}.{}()".format(
                        module_short_name,
                        class_name
                    )
                )

            lines.append("```")
            return "\n".join(lines)

    if class_info is None:
        call_name = "{}.{}".format(
            module_short_name,
            callable_info["name"]
        )

        if module_info["module_name"] == "muziToolset":
            call_name = "muziToolset.{}".format(
                callable_info["name"]
            )

    else:
        class_name = class_info["name"]
        constructor = class_info["constructor"]

        constructor_required = []

        if constructor:
            constructor_required = get_required_parameters(
                constructor["parameters"]
            )

        if constructor_required:
            lines.append(
                "{} = {}.{}(".format(
                    "instance",
                    module_short_name,
                    class_name
                )
            )

            for parameter in constructor_required:
                lines.append(
                    "    {}={}".format(
                        parameter["name"],
                        build_parameter_placeholder(
                            parameter
                        )
                    ) + ","
                )

            lines.append(")")
        else:
            lines.append(
                "instance = {}.{}()".format(
                    module_short_name,
                    class_name
                )
            )

        lines.append("")
        call_name = "instance.{}".format(
            callable_info["name"]
        )

    if required_parameters:
        lines.append(
            "result = {}(".format(
                call_name
            )
        )

        for parameter in required_parameters:
            lines.append(
                "    {}={}".format(
                    parameter["name"],
                    build_parameter_placeholder(
                        parameter
                    )
                ) + ","
            )

        lines.append(")")
    else:
        lines.append(
            "result = {}()".format(
                call_name
            )
        )

    lines.append("```")
    return "\n".join(lines)


def build_docstring_example(example_text):
    """把 Docstring Example 区域整理为 Markdown Python Code Block。"""
    if not example_text:
        return ""

    stripped_text = example_text.strip()

    if stripped_text.startswith("```"):
        return stripped_text

    lines = stripped_text.splitlines()
    clean_lines = []

    for line in lines:
        clean_line = line

        if clean_line.lstrip().startswith(">>> "):
            clean_line = clean_line.replace(
                ">>> ",
                "",
                1
            )

        elif clean_line.lstrip().startswith("... "):
            clean_line = clean_line.replace(
                "... ",
                "",
                1
            )

        clean_lines.append(
            clean_line
        )

    return "```python\n{}\n```".format(
        "\n".join(clean_lines)
    )


def build_parameter_table(callable_info):
    """生成一个 Function / Method 的参数表格。"""
    visible_parameters = []

    for parameter in callable_info["parameters"]:
        if parameter["name"] in ["self", "cls"]:
            continue

        visible_parameters.append(
            parameter
        )

    if not visible_parameters:
        return [
            "无。",
            "",
        ]

    lines = []
    lines.append(
        "| 参数 | 类型 | 必填 | 默认值 | 说明 |"
    )
    lines.append(
        "| --- | --- | :---: | --- | --- |"
    )

    for parameter in visible_parameters:
        parameter_type = (
            parameter["doc_type"]
            or parameter["type"]
            or "未声明"
        )

        required_text = "是"

        if not parameter["required"]:
            required_text = "否"

        default_text = parameter["default"]

        if not default_text:
            if parameter["kind"] == "vararg":
                default_text = "*args"
            elif parameter["kind"] == "kwarg":
                default_text = "**kwargs"
            else:
                default_text = "—"

        description = parameter["description"]

        if not description:
            description = "源码暂未提供单独参数说明。"

        lines.append(
            "| `{}` | `{}` | {} | `{}` | {} |".format(
                escape_table_text(
                    parameter["name"]
                ),
                escape_table_text(
                    parameter_type
                ),
                required_text,
                escape_table_text(
                    default_text
                ),
                escape_table_text(
                    description
                )
            )
        )

    lines.append("")
    return lines


def append_callable_markdown(
        lines,
        module_info,
        callable_info,
        heading_level,
        class_info=None
):
    """把一个 Function / Method 的完整 API 文档追加到 Markdown。"""
    heading = "#" * heading_level

    lines.append(
        "{} `{}`".format(
            heading,
            callable_info["name"] + "()"
        )
    )
    lines.append("")

    summary = callable_info["summary"]

    if not summary:
        summary = "源码暂未提供详细功能摘要。"

    lines.append(
        summary
    )
    lines.append("")

    if callable_info["usage"]:
        lines.append(
            "**适用场景**"
        )
        lines.append("")
        lines.append(
            callable_info["usage"]
        )
        lines.append("")

    if callable_info["body"]:
        lines.append(
            callable_info["body"]
        )
        lines.append("")

    # -------------------------------------------------------------------------
    # Signature
    # -------------------------------------------------------------------------
    lines.append(
        "**Signature**"
    )
    lines.append("")
    lines.append("```python")
    lines.append(
        callable_info["signature"]
    )
    lines.append("```")
    lines.append("")

    # -------------------------------------------------------------------------
    # 参数
    # -------------------------------------------------------------------------
    lines.append(
        "**参数**"
    )
    lines.append("")
    parameter_lines = build_parameter_table(
        callable_info
    )

    for parameter_line in parameter_lines:
        lines.append(
            parameter_line
        )

    # -------------------------------------------------------------------------
    # 返回值
    # -------------------------------------------------------------------------
    lines.append(
        "**返回值**"
    )
    lines.append("")

    if callable_info["returns"]:
        lines.append(
            callable_info["returns"]
        )
    elif callable_info["return_annotation"]:
        lines.append(
            "返回类型：`{}`。源码暂未提供更详细的返回值说明。".format(
                callable_info[
                    "return_annotation"
                ]
            )
        )
    else:
        lines.append(
            "源码未声明返回值说明。"
        )

    lines.append("")

    # -------------------------------------------------------------------------
    # 异常
    # -------------------------------------------------------------------------
    lines.append(
        "**异常**"
    )
    lines.append("")

    if callable_info["raises"]:
        for raise_info in callable_info["raises"]:
            description = raise_info[
                "description"
            ]

            if not description:
                description = "源码未提供进一步说明。"

            lines.append(
                "- `{}`：{}".format(
                    raise_info["type"],
                    description
                )
            )
    else:
        lines.append(
            "源码未声明专门的异常说明。"
        )

    lines.append("")

    # -------------------------------------------------------------------------
    # 示例
    # -------------------------------------------------------------------------
    lines.append(
        "**示例**"
    )
    lines.append("")

    if callable_info["examples"]:
        lines.append(
            build_docstring_example(
                callable_info["examples"]
            )
        )
    else:
        lines.append(
            build_callable_example(
                module_info,
                callable_info,
                class_info=class_info
            )
        )

    lines.append("")

    # -------------------------------------------------------------------------
    # Notes
    # -------------------------------------------------------------------------
    if callable_info["notes"]:
        lines.append(
            '!!! note "说明"'
        )

        for note_line in callable_info["notes"].splitlines():
            lines.append(
                "    " + note_line
            )

        lines.append("")


# =============================================================================
# 单模块 Markdown
# =============================================================================

def build_module_markdown(module_info):
    """生成一个正式 Python 文件对应的详细 API Reference。"""
    lines = []
    lines.append(
        generated_marker
    )
    lines.append("")
    lines.append(
        "# `{}`".format(
            module_info["module_name"]
        )
    )
    lines.append("")
    lines.append(
        "> 本页由 `scripts/generate_mkdocs_reference.py` 根据当前源码 AST 自动生成。"
    )
    lines.append(
        "> 源码 Docstring 是参数、返回值、异常和示例说明的第一事实来源。"
    )
    lines.append("")

    # -------------------------------------------------------------------------
    # 概览
    # -------------------------------------------------------------------------
    lines.append(
        "## 概览"
    )
    lines.append("")

    summary = module_info["summary"]

    if not summary:
        summary = "当前模块尚未提供完整模块摘要。"

    lines.append(
        summary
    )
    lines.append("")

    if module_info["body"]:
        lines.append(
            module_info["body"]
        )
        lines.append("")

    # -------------------------------------------------------------------------
    # 常用任务
    # -------------------------------------------------------------------------
    lines.append(
        "## 常用任务"
    )
    lines.append("")

    scenarios = build_usage_scenarios(
        module_info
    )

    for scenario in scenarios:
        lines.append(
            "- " + scenario
        )

    lines.append("")

    # -------------------------------------------------------------------------
    # Import
    # -------------------------------------------------------------------------
    lines.append(
        "## Import"
    )
    lines.append("")
    lines.append("```python")
    lines.append(
        build_import_example(
            module_info
        )
    )
    lines.append("```")
    lines.append("")

    # -------------------------------------------------------------------------
    # API 一览
    # -------------------------------------------------------------------------
    lines.append(
        "## API 一览"
    )
    lines.append("")

    has_public_api = False

    if module_info["functions"]:
        has_public_api = True

        lines.append(
            "### Functions"
        )
        lines.append("")
        lines.append(
            "| API | 作用 |"
        )
        lines.append(
            "| --- | --- |"
        )

        for function_info in module_info["functions"]:
            summary = (
                function_info["summary"]
                or "源码暂未提供摘要。"
            )

            lines.append(
                "| `{}` | {} |".format(
                    escape_table_text(
                        function_info["signature"]
                    ),
                    escape_table_text(
                        summary
                    )
                )
            )

        lines.append("")

    for class_info in module_info["classes"]:
        has_public_api = True

        lines.append(
            "### Class `{}`".format(
                class_info["name"]
            )
        )
        lines.append("")

        class_summary = (
            class_info["summary"]
            or "源码暂未提供类说明。"
        )

        lines.append(
            class_summary
        )
        lines.append("")

        if class_info["methods"]:
            lines.append(
                "| Method | 作用 |"
            )
            lines.append(
                "| --- | --- |"
            )

            for method_info in class_info["methods"]:
                method_summary = (
                    method_info["summary"]
                    or "源码暂未提供摘要。"
                )

                lines.append(
                    "| `{}` | {} |".format(
                        escape_table_text(
                            method_info["signature"]
                        ),
                        escape_table_text(
                            method_summary
                        )
                    )
                )

            lines.append("")

    if not has_public_api:
        lines.append(
            "当前文件没有检测到公开 Function / Class。"
        )
        lines.append("")

    # -------------------------------------------------------------------------
    # 常量
    # -------------------------------------------------------------------------
    if module_info["constants"]:
        lines.append(
            "## 公共常量"
        )
        lines.append("")
        lines.append(
            "| 名称 | 值 |"
        )
        lines.append(
            "| --- | --- |"
        )

        for constant_info in module_info["constants"]:
            lines.append(
                "| `{}` | `{}` |".format(
                    escape_table_text(
                        constant_info["name"]
                    ),
                    escape_table_text(
                        constant_info["value"]
                    )
                )
            )

        lines.append("")

    # -------------------------------------------------------------------------
    # Functions 详细 API
    # -------------------------------------------------------------------------
    if module_info["functions"]:
        lines.append(
            "## Functions 详细 API"
        )
        lines.append("")

        for function_info in module_info["functions"]:
            append_callable_markdown(
                lines,
                module_info,
                function_info,
                heading_level=3,
                class_info=None
            )

    # -------------------------------------------------------------------------
    # Classes 详细 API
    # -------------------------------------------------------------------------
    if module_info["classes"]:
        lines.append(
            "## Classes 详细 API"
        )
        lines.append("")

        for class_info in module_info["classes"]:
            lines.append(
                "### `{}`".format(
                    class_info["name"]
                )
            )
            lines.append("")

            class_summary = (
                class_info["summary"]
                or "源码暂未提供类说明。"
            )

            lines.append(
                class_summary
            )
            lines.append("")

            if class_info["usage"]:
                lines.append(
                    "**适用场景**"
                )
                lines.append("")
                lines.append(
                    class_info["usage"]
                )
                lines.append("")

            if class_info["body"]:
                lines.append(
                    class_info["body"]
                )
                lines.append("")

            constructor = class_info["constructor"]

            if constructor:
                append_callable_markdown(
                    lines,
                    module_info,
                    constructor,
                    heading_level=4,
                    class_info=class_info
                )

            for method_info in class_info["methods"]:
                append_callable_markdown(
                    lines,
                    module_info,
                    method_info,
                    heading_level=4,
                    class_info=class_info
                )

            if class_info["notes"]:
                lines.append(
                    '!!! note "Class Notes"'
                )

                for note_line in class_info["notes"].splitlines():
                    lines.append(
                        "    " + note_line
                    )

                lines.append("")

    # -------------------------------------------------------------------------
    # 源码位置
    # -------------------------------------------------------------------------
    lines.append(
        "## 源码位置"
    )
    lines.append("")
    lines.append(
        "`{}`".format(
            module_info["relative_path"]
        )
    )
    lines.append("")

    return "\n".join(
        lines
    )


# =============================================================================
# Output Path / Index
# =============================================================================

def get_output_relative_path(module_info):
    """计算源码文件对应的 ``docs/reference`` 输出路径。"""
    relative_source = module_info[
        "relative_path"
    ]

    if relative_source == "__init__.py":
        return "package.md"

    if relative_source.endswith("/__init__.py"):
        package_directory = os.path.dirname(
            relative_source
        )

        return os.path.join(
            package_directory,
            "package.md"
        )

    relative_without_extension = os.path.splitext(
        relative_source
    )[0]

    return relative_without_extension + ".md"


def write_text_file(file_path, content):
    """写入 UTF-8 文本，并自动创建父目录。"""
    parent_directory = os.path.dirname(
        file_path
    )

    if not os.path.isdir(parent_directory):
        os.makedirs(
            parent_directory
        )

    with open(
            file_path,
            "w",
            encoding="utf-8",
            newline="\n"
    ) as file_object:
        file_object.write(
            content
        )


def build_reference_tree(module_items, category_name):
    """把模块列表整理成按源码目录分组的 Reference Index。"""
    grouped_items = {}

    for module_info, output_path in module_items:
        relative_path = module_info[
            "relative_path"
        ]

        if category_name == "package":
            group_name = "Package"
        else:
            relative_from_category = os.path.relpath(
                relative_path,
                category_name
            ).replace(
                "\\",
                "/"
            )

            group_directory = os.path.dirname(
                relative_from_category
            )

            if not group_directory:
                group_name = "基础模块"
            else:
                group_name = group_directory

        if group_name not in grouped_items:
            grouped_items[group_name] = []

        grouped_items[group_name].append(
            (module_info, output_path)
        )

    return grouped_items


def build_reference_index(
        title,
        description,
        module_items,
        docs_root,
        category_name
):
    """生成一个 API 分类索引。"""
    lines = []
    lines.append(
        generated_marker
    )
    lines.append("")
    lines.append(
        "# {}".format(
            title
        )
    )
    lines.append("")
    lines.append(
        description
    )
    lines.append("")

    grouped_items = build_reference_tree(
        module_items,
        category_name
    )

    group_names = list(
        grouped_items.keys()
    )
    group_names.sort()

    for group_name in group_names:
        lines.append(
            "## {}".format(
                group_name
            )
        )
        lines.append("")

        index_directory = os.path.join(
            docs_root,
            "reference",
            category_name
        )

        if category_name == "package":
            index_directory = os.path.join(
                docs_root,
                "reference"
            )

        group_items = grouped_items[
            group_name
        ]

        def get_group_item_sort_key(item):
            """返回 Reference Index 项目的稳定排序键。"""
            module_info = item[0]
            return module_info["relative_path"]

        group_items.sort(
            key=get_group_item_sort_key
        )

        for module_info, output_path in group_items:
            relative_link = os.path.relpath(
                output_path,
                index_directory
            ).replace(
                "\\",
                "/"
            )

            summary = (
                module_info["summary"]
                or "查看该文件的公开 API。"
            )

            lines.append(
                "- [`{}`]({}) — {}".format(
                    module_info["relative_path"],
                    relative_link,
                    summary
                )
            )

        lines.append("")

    return "\n".join(
        lines
    )


def clean_generated_reference(reference_root):
    """删除旧自动生成页面，但保留手写 User Guide。"""
    if not os.path.isdir(reference_root):
        return

    for root_directory, folder_names, file_names in os.walk(reference_root):
        for file_name in file_names:
            if not file_name.endswith(".md"):
                continue

            file_path = os.path.join(
                root_directory,
                file_name
            )

            try:
                with open(
                        file_path,
                        "r",
                        encoding="utf-8"
                ) as file_object:
                    first_content = file_object.read(
                        512
                    )
            except OSError:
                continue

            if generated_marker not in first_content:
                continue

            os.remove(
                file_path
            )

    for root_directory, folder_names, file_names in os.walk(
            reference_root,
            topdown=False
    ):
        if root_directory == reference_root:
            continue

        if os.listdir(root_directory):
            continue

        shutil.rmtree(
            root_directory
        )


# =============================================================================
# Navigation Data
# =============================================================================

def build_api_navigation(module_infos):
    """
    生成 API Reference 的分类统计。

    MkDocs 真正的左侧导航由 SUMMARY.md 提供。
    """
    category_names = [
        "app",
        "core",
        "systems",
        "tools",
        "ui",
        "package",
    ]

    navigation = {}

    for category_name in category_names:
        navigation[category_name] = []

    for module_info in module_infos:
        category_name = module_info[
            "root_name"
        ]

        if category_name not in navigation:
            navigation[category_name] = []

        navigation[category_name].append(
            module_info["relative_path"]
        )

    for category_name in navigation:
        navigation[category_name].sort()

    return navigation


# =============================================================================
# MkDocs Literate Navigation
# =============================================================================

def get_navigation_display_name(name):
    """把源码目录 / 文件名称转换成更适合侧边栏显示的标题。"""
    special_names = {
        "app": "App",
        "core": "Core",
        "systems": "Systems",
        "tools": "Tools",
        "ui": "UI",
        "face": "Face",
        "eyelid": "Eyelid",
        "lip": "Lip",
        "controller": "Controller",
        "blendshape": "BlendShape",
        "skin": "Skin",
        "joint": "Joint",
        "basic": "Basic",
        "clean": "Clean",
        "rig": "Rig",
        "body": "Body",
        "skirt": "Skirt",
        "widgets": "Widgets",
    }

    if name in special_names:
        return special_names[name]

    display_name = name

    if display_name.endswith(".py"):
        display_name = display_name[:-3]

    display_name = display_name.replace(
        "_",
        " "
    )

    words = display_name.split()
    result_words = []

    for word in words:
        if not word:
            continue

        result_words.append(
            word[0].upper() + word[1:]
        )

    return " ".join(
        result_words
    )


def build_module_navigation_tree(
        module_infos,
        category_name
):
    """根据源码目录构建某个 API 分类的导航树。"""
    tree = {
        "__modules__": [],
    }

    for module_info in module_infos:
        if module_info["root_name"] != category_name:
            continue

        relative_path = module_info[
            "relative_path"
        ]

        if category_name == "package":
            path_parts = [
                relative_path
            ]
        else:
            relative_from_category = os.path.relpath(
                relative_path,
                category_name
            ).replace(
                "\\",
                "/"
            )

            path_parts = relative_from_category.split(
                "/"
            )

        current_tree = tree

        directory_parts = path_parts[:-1]
        file_name = path_parts[-1]

        for directory_name in directory_parts:
            if directory_name not in current_tree:
                current_tree[directory_name] = {
                    "__modules__": [],
                }

            current_tree = current_tree[
                directory_name
            ]

        current_tree["__modules__"].append({
            "file_name": file_name,
            "module_info": module_info,
        })

    return tree


def render_module_navigation_tree(
        tree,
        lines,
        indent_level
):
    """递归把模块导航树渲染成 mkdocs-literate-nav Markdown。"""
    indent = "    " * indent_level

    modules = tree.get(
        "__modules__",
        []
    )

    # Package 页面优先，其余按源码文件名排序。
    def get_module_sort_key(module_item):
        """返回导航中文件的稳定排序键。"""
        file_name = module_item[
            "file_name"
        ]

        if file_name == "__init__.py":
            return "0"

        return "1_" + file_name

    modules.sort(
        key=get_module_sort_key
    )

    for module_item in modules:
        module_info = module_item[
            "module_info"
        ]
        file_name = module_item[
            "file_name"
        ]

        output_relative_path = get_output_relative_path(
            module_info
        ).replace(
            "\\",
            "/"
        )

        link_path = "reference/" + output_relative_path

        if file_name == "__init__.py":
            display_name = "Package"
        else:
            display_name = "`{}`".format(
                file_name
            )

        lines.append(
            "{}* [{}]({})".format(
                indent,
                display_name,
                link_path
            )
        )

    directory_names = []

    for key in tree:
        if key == "__modules__":
            continue

        directory_names.append(
            key
        )

    directory_names.sort()

    for directory_name in directory_names:
        display_name = get_navigation_display_name(
            directory_name
        )

        lines.append(
            "{}* {}".format(
                indent,
                display_name
            )
        )

        child_tree = tree[
            directory_name
        ]

        render_module_navigation_tree(
            child_tree,
            lines,
            indent_level + 1
        )


def build_summary_markdown(module_infos):
    """
    生成 docs/SUMMARY.md。

    这份文件由 mkdocs-literate-nav 读取，负责把自动生成的每个 API 文件
    真正展示到左侧导航中。
    """
    lines = []

    # -------------------------------------------------------------------------
    # Apple 风格：先是任务导向 User Guide，再是 Developer API。
    # -------------------------------------------------------------------------
    lines.append(
        "* [首页](index.md)"
    )

    lines.append(
        "* 用户手册"
    )
    lines.append(
        "    * [用户手册首页](manual/index.md)"
    )
    lines.append(
        "    * [安装与启动](getting-started/installation.md)"
    )
    lines.append(
        "    * [在 Maya 中运行](getting-started/maya-usage.md)"
    )
    lines.append(
        "    * [常用工具工作流](manual/tools.md)"
    )
    lines.append(
        "    * [绑定工作流](manual/rigging.md)"
    )
    lines.append(
        "    * [Face Guide](manual/face-guide.md)"
    )

    lines.append(
        "* 架构"
    )
    lines.append(
        "    * [总体架构](architecture/index.md)"
    )
    lines.append(
        "    * [Core 设计](architecture/core.md)"
    )
    lines.append(
        "    * [Tools 与 Systems](architecture/tools-systems.md)"
    )

    lines.append(
        "* API 参考"
    )
    lines.append(
        "    * [API 总览](reference/index.md)"
    )

    category_settings = [
        (
            "package",
            "根包",
            "reference/package-index.md"
        ),
        (
            "app",
            "App",
            "reference/app/index.md"
        ),
        (
            "core",
            "Core",
            "reference/core/index.md"
        ),
        (
            "tools",
            "Tools",
            "reference/tools/index.md"
        ),
        (
            "systems",
            "Systems",
            "reference/systems/index.md"
        ),
        (
            "ui",
            "UI",
            "reference/ui/index.md"
        ),
    ]

    for category_name, display_name, index_path in category_settings:
        has_category = False

        for module_info in module_infos:
            if module_info["root_name"] == category_name:
                has_category = True
                break

        if not has_category:
            continue

        lines.append(
            "    * [{}]({})".format(
                display_name,
                index_path
            )
        )

        tree = build_module_navigation_tree(
            module_infos,
            category_name
        )

        render_module_navigation_tree(
            tree,
            lines,
            indent_level=2
        )

    lines.append(
        "* 开发指南"
    )
    lines.append(
        "    * [文档维护](development/documentation.md)"
    )
    lines.append(
        "    * [Core 编码规范](development/core-style-guide.md)"
    )
    lines.append(
        "    * [测试](development/testing.md)"
    )

    lines.append(
        "* 迁移记录"
    )
    lines.append(
        "    * [Pipeline 重构](migration/pipeline.md)"
    )

    lines.append("")
    return "\n".join(
        lines
    )


def write_summary_file(
        docs_root,
        module_infos
):
    """生成 MkDocs 左侧导航使用的 SUMMARY.md。"""
    summary_content = build_summary_markdown(
        module_infos
    )

    summary_path = os.path.join(
        docs_root,
        "SUMMARY.md"
    )

    write_text_file(
        summary_path,
        summary_content
    )

    return summary_path


# =============================================================================
# Generate
# =============================================================================

def generate_reference_docs(project_root=None):
    """
    扫描正式源码并生成全部详细 API Reference。

    Returns:
        dict:
            generated_modules / output_files / navigation。
    """
    if project_root is None:
        project_root = get_project_root()

    docs_root = get_docs_root(
        project_root
    )

    reference_root = os.path.join(
        docs_root,
        "reference"
    )

    clean_generated_reference(
        reference_root
    )

    source_files = iter_source_files(
        project_root
    )
    module_infos = []

    for source_path in source_files:
        module_info = collect_module_info(
            project_root,
            source_path
        )

        module_infos.append(
            module_info
        )

    output_files = []
    category_items = {
        "app": [],
        "core": [],
        "systems": [],
        "tools": [],
        "ui": [],
        "package": [],
    }

    for module_info in module_infos:
        output_relative_path = get_output_relative_path(
            module_info
        )

        output_path = os.path.join(
            reference_root,
            output_relative_path
        )

        markdown_content = build_module_markdown(
            module_info
        )

        write_text_file(
            output_path,
            markdown_content
        )

        output_files.append(
            output_path
        )

        category_name = module_info[
            "root_name"
        ]

        if category_name not in category_items:
            category_items[category_name] = []

        category_items[category_name].append(
            (
                module_info,
                output_path
            )
        )

    category_settings = {
        "app": (
            "App API",
            "App 层负责 MuziTools 主程序入口、工具箱和顶层窗口生命周期。"
        ),
        "core": (
            "Core API",
            "Core 是 Maya 通用底层能力层，不包含完整 Rig Workflow。"
        ),
        "systems": (
            "Systems API",
            "Systems 是可复用的完整 Rig Builder / Workflow。"
        ),
        "tools": (
            "Tools API",
            "Tools 是绑定师可以直接打开使用的小工具和操作面板。"
        ),
        "ui": (
            "UI API",
            "UI 层提供统一窗口、主题和可复用 PySide 组件。"
        ),
        "package": (
            "Package API",
            "MuziTools 根包和全局配置入口。"
        ),
    }

    for category_name in category_settings:
        module_items = category_items.get(
            category_name,
            []
        )

        if not module_items:
            continue

        title, description = category_settings[
            category_name
        ]

        index_content = build_reference_index(
            title,
            description,
            module_items,
            docs_root,
            category_name
        )

        if category_name == "package":
            index_path = os.path.join(
                reference_root,
                "package-index.md"
            )
        else:
            index_path = os.path.join(
                reference_root,
                category_name,
                "index.md"
            )

        write_text_file(
            index_path,
            index_content
        )

        output_files.append(
            index_path
        )

    navigation = build_api_navigation(
        module_infos
    )

    summary_path = write_summary_file(
        docs_root,
        module_infos
    )
    output_files.append(
        summary_path
    )

    return {
        "generated_modules": len(
            module_infos
        ),
        "output_files": output_files,
        "navigation": navigation,
        "summary_path": summary_path,
    }


# =============================================================================
# Command Line
# =============================================================================

def main():
    """生成全部 API Reference，并打印生成统计。"""
    result = generate_reference_docs()

    print("=" * 78)
    print("MuziTools MkDocs Reference Generator")
    print("=" * 78)
    print(
        "Generated modules: {}".format(
            result["generated_modules"]
        )
    )
    print(
        "Generated files:   {}".format(
            len(
                result["output_files"]
            )
        )
    )

    print("Categories:")

    for category_name in result["navigation"]:
        print(
            "  {:<10} {}".format(
                category_name,
                len(
                    result["navigation"][
                        category_name
                    ]
                )
            )
        )

    print("=" * 78)

    return result


if __name__ == "__main__":
    main()
