# coding=utf-8
u"""
Generated Callable Layout Validator
===================================

检查自动生成 API Reference 中每个 Function / Method 是否在标题后明确显示“作用”。

本脚本只做最终布局验证；实际“作用”区块由 refine_generated_reference.py 统一写入。
"""

from __future__ import print_function

import argparse
import os
import re
import sys


GENERATED_MARKER = "<!-- AUTO-GENERATED BY scripts/generate_mkdocs_reference.py -->"

CALLABLE_HEADING_PATTERN = re.compile(
    r"^(#{3,6})\s+`[^`]+\(\)`\s*$"
)


# =============================================================================
# Project
# =============================================================================

def get_project_root():
    u"""返回 MuziTools 仓库根目录。"""
    script_directory = os.path.dirname(
        os.path.abspath(__file__)
    )
    return os.path.dirname(
        script_directory
    )


def iter_generated_reference_files(project_root):
    u"""扫描全部自动生成 Runtime API Reference Markdown。"""
    reference_root = os.path.join(
        project_root,
        "docs",
        "reference"
    )
    markdown_files = []

    if not os.path.isdir(reference_root):
        return markdown_files

    for current_root, folder_names, file_names in os.walk(reference_root):
        if "__pycache__" in folder_names:
            folder_names.remove(
                "__pycache__"
            )

        for file_name in file_names:
            if not file_name.endswith(".md"):
                continue

            file_path = os.path.join(
                current_root,
                file_name
            )

            with open(
                    file_path,
                    "r",
                    encoding="utf-8"
            ) as file_object:
                prefix = file_object.read(512)

            if GENERATED_MARKER not in prefix:
                continue

            markdown_files.append(
                file_path
            )

    markdown_files.sort()
    return markdown_files


# =============================================================================
# Validate
# =============================================================================

def validate_markdown_text(markdown_text, relative_path):
    u"""检查所有 Function / Method Heading 后都存在“作用”区域。"""
    errors = []
    callable_count = 0
    lines = markdown_text.splitlines()

    line_index = 0

    while line_index < len(lines):
        line = lines[line_index]

        if not CALLABLE_HEADING_PATTERN.match(line):
            line_index += 1
            continue

        callable_count += 1
        next_index = line_index + 1

        while next_index < len(lines):
            if lines[next_index].strip():
                break

            next_index += 1

        if next_index >= len(lines):
            errors.append(
                u"{}:{} 方法标题后缺少作用说明。".format(
                    relative_path,
                    line_index + 1
                )
            )
            line_index += 1
            continue

        if lines[next_index].strip() != "**作用**":
            errors.append(
                u"{}:{} 方法标题后没有固定的“作用”区域。".format(
                    relative_path,
                    line_index + 1
                )
            )

        line_index += 1

    return callable_count, errors


def run():
    u"""检查全部生成 API 页面。"""
    project_root = get_project_root()
    markdown_files = iter_generated_reference_files(
        project_root
    )

    if not markdown_files:
        print(u"没有找到自动生成 API 页面。")
        return False

    errors = []
    callable_count = 0

    for file_path in markdown_files:
        with open(
                file_path,
                "r",
                encoding="utf-8"
        ) as file_object:
            markdown_text = file_object.read()

        relative_path = os.path.relpath(
            file_path,
            project_root
        )

        file_callable_count, file_errors = validate_markdown_text(
            markdown_text,
            relative_path
        )

        callable_count += file_callable_count

        for error in file_errors:
            errors.append(
                error
            )

    print("=" * 78)
    print("Generated Callable Layout")
    print("=" * 78)
    print("Reference files: {}".format(len(markdown_files)))
    print("Callable count:  {}".format(callable_count))
    print("Layout errors:   {}".format(len(errors)))

    if callable_count <= 0:
        errors.append(
            u"没有扫描到任何公开 Function / Method。"
        )

    if errors:
        for error in errors:
            print(
                "  - " + error
            )

        print("=" * 78)
        return False

    print("Status:          PASS")
    print("=" * 78)
    return True


def main():
    u"""命令行入口。"""
    parser = argparse.ArgumentParser(
        description="Validate Function / Method purpose in generated API Reference."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate that every callable has a purpose section."
    )

    parser.parse_args()

    success = run()

    if not success:
        sys.exit(1)


if __name__ == "__main__":
    main()
